directories:
  output: release
  buildResources: build
appId: com.hyperspace.player
productName: Hyperspace
mac:
  category: public.app-category.music
  target:
    - dmg
  icon: build/icon.png
win:
  target:
    - nsis
  icon: build/icon.ico
files:
  - filter:
      - dist/**/*
      - main.js
electronVersion: 27.3.11
